server:
  port: 8082

spring:
  redis:
    host: 192.168.163.142
    port: 6379
    password: lims
    jedis:
      pool:
        max-active: 1024
        max-wait: 20000
        max-idle: 200
        min-idle: 0
    timeout: 10000  #超时时间
